### ISSUE TITLE
Unable to connect to server: zk2:2181

### ISSUE THREAD

**Issue by mrhjx2** [cookeem/kubernetes-zookeeper-cluster#1]
2018-06-29 02:46:47,330 [myid:] - INFO  [main:Environment@100] - Client environment:java.home=/usr/lib/jvm/java-1.8-openjdk/jre
2018-06-29 02:46:47,331 [myid:] - INFO  [main:Environment@100] - Client environment:java.class.path=/zookeeper-3.4.12/bin/../build/classes:/zookeeper-3.4.12/bin/../build/lib/*.jar:/zookeeper-3.4.12/bin/../lib/slf4j-log4j12-1.7.25.jar:/zookeeper-3.4.12/bin/../lib/slf4j-api-1.7.25.jar:/zookeeper-3.4.12/bin/../lib/netty-3.10.6.Final.jar:/zookeeper-3.4.12/bin/../lib/log4j-1.2.17.jar:/zookeeper-3.4.12/bin/../lib/jline-0.9.94.jar:/zookeeper-3.4.12/bin/../lib/audience-annotations-0.5.0.jar:/zookeeper-3.4.12/bin/../zookeeper-3.4.12.jar:/zookeeper-3.4.12/bin/../src/java/lib/*.jar:/conf:
2018-06-29 02:46:47,331 [myid:] - INFO  [main:Environment@100] - Client environment:java.library.path=/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2018-06-29 02:46:47,331 [myid:] - INFO  [main:Environment@100] - Client environment:java.io.tmpdir=/tmp
2018-06-29 02:46:47,331 [myid:] - INFO  [main:Environment@100] - Client environment:java.compiler=<NA>
2018-06-29 02:46:47,331 [myid:] - INFO  [main:Environment@100] - Client environment:os.name=Linux
2018-06-29 02:46:47,331 [myid:] - INFO  [main:Environment@100] - Client environment:os.arch=amd64
2018-06-29 02:46:47,331 [myid:] - INFO  [main:Environment@100] - Client environment:os.version=3.10.0-693.21.1.el7.x86_64
2018-06-29 02:46:47,331 [myid:] - INFO  [main:Environment@100] - Client environment:user.name=root
2018-06-29 02:46:47,331 [myid:] - INFO  [main:Environment@100] - Client environment:user.home=/root
2018-06-29 02:46:47,332 [myid:] - INFO  [main:Environment@100] - Client environment:user.dir=/zookeeper-3.4.12
2018-06-29 02:46:47,334 [myid:] - INFO  [main:ZooKeeper@441] - Initiating client connection, connectString=zk2:2181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@446cdf90
2018-06-29 02:46:47,343 [myid:] - ERROR [main:StaticHostProvider@83] - Unable to connect to server: zk2:2181
java.net.UnknownHostException: zk2: Name does not resolve
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:62)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:449)
	at org.apache.zookeeper.ZooKeeperMain.connectToZK(ZooKeeperMain.java:283)
	at org.apache.zookeeper.ZooKeeperMain.<init>(ZooKeeperMain.java:297)
	at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:290)
Exception in thread "main" java.lang.IllegalArgumentException: A HostProvider may not be empty!
	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:88)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:449)
	at org.apache.zookeeper.ZooKeeperMain.connectToZK(ZooKeeperMain.java:283)
	at org.apache.zookeeper.ZooKeeperMain.<init>(ZooKeeperMain.java:297)
	at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:290)

I get a error logs  but nodes is runing

**Comment by cookeem** [comment]
The service name should be zk-2 not zk2.
```
2018-06-29 02:46:47,343 [myid:] - ERROR [main:StaticHostProvider@83] - Unable to connect to server: zk2:2181
```

**Comment by mrhjx2** [comment]
I try to find zk2 in my config but there's no zk2 word in my deployment and service config file
zk-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: zk-1
  labels:
    app: zk
    node: node1
spec:
  type: LoadBalancer
  ports:
  - name: port-2181
    port: 2181
  - name: port-2888
    port: 2888
  - name: port-3888
    port: 3888
  selector:
    app: zk
    node: node1

---
kind: Service
apiVersion: v1
metadata:
  name: zk-2
  labels:
    app: zk
    node: node2
spec:
  type: LoadBalancer
  ports:
  - name: port-2181
    port: 2181
  - name: port-2888
    port: 2888
  - name: port-3888
    port: 3888
  selector:
    app: zk
    node: node2
zk-deployment.yaml
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zk-0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zk
        node: node0
    spec:
      hostname: zk-0
      volumes:
        - name: zk-data
          hostPath: 
            path: /data/zk-cluster/zk-data-0
        - name: zk-logs
          hostPath: 
            path: /data/zk-cluster/zk-logs-0
      containers:
      - name: zk-0
        image: zookeeper
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: zk-data
          readOnly: false
          mountPath: "/data/zk-data"
        - name: zk-logs
          readOnly: false
          mountPath: "/data/zk-logs"
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        #command: ['tail', '-f', '/etc/hosts']  
        env:
        - name: ZOO_MY_ID
          value: '0'
        - name: ZOO_SERVERS
          # 注意！！k8s使用到virtual ip，因此，本机必须使用0.0.0.0 ip地址，否则本机zk启动会异常：
          # ERROR [zk1/10.0.0.251:3888:QuorumCnxManager$Listener@547] - Exception while listening
          # java.net.BindException: Address not available (Bind failed)错误
          value: server.0=0.0.0.0:2888:3888 server.1=zk-1:2888:3888 server.2=zk-2:2888:3888
        - name: ZOO_DATA_DIR
          value: '/data/zk-data'
        - name: ZOO_DATA_LOG_DIR
          value: '/data/zk-logs'  

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zk-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zk
        node: node1
    spec:
      hostname: zk-1
      volumes:
        - name: zk-data
          hostPath: 
            path: /data/zk-cluster/zk-data-1
        - name: zk-logs
          hostPath: 
            path: /data/zk-cluster/zk-logs-1
      containers:
      - name: zk-1
        image: zookeeper
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: zk-data
          readOnly: false
          mountPath: "/data/zk-data"
        - name: zk-logs
          readOnly: false
          mountPath: "/data/zk-logs"
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        #command: ['tail', '-f', '/etc/hosts']  
        env:
        - name: ZOO_MY_ID
          value: '1'
        - name: ZOO_SERVERS
          # 注意！！k8s使用到virtual ip，因此，本机必须使用0.0.0.0 ip地址，否则本机zk启动会异常：
          # ERROR [zk1/10.0.0.251:3888:QuorumCnxManager$Listener@547] - Exception while listening
          # java.net.BindException: Address not available (Bind failed)错误
          value: server.0=zk-0:2888:3888 server.1=0.0.0.0:2888:3888 server.2=zk-2:2888:3888
        - name: ZOO_DATA_DIR
          value: '/data/zk-data'
        - name: ZOO_DATA_LOG_DIR
          value: '/data/zk-logs'  

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zk-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zk
        node: node2
    spec:
      hostname: zk-2
      volumes:
        - name: zk-data
          hostPath: 
            path: /data/zk-cluster/zk-data-2
        - name: zk-logs
          hostPath: 
            path: /data/zk-cluster/zk-logs-2
      containers:
      - name: zk-2
        image: zookeeper
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: zk-data
          readOnly: false
          mountPath: "/data/zk-data"
        - name: zk-logs
          readOnly: false
          mountPath: "/data/zk-logs"
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        #command: ['tail', '-f', '/etc/hosts']  
        env:
        - name: ZOO_MY_ID
          value: '2'
        - name: ZOO_SERVERS
          # 注意！！k8s使用到virtual ip，因此，本机必须使用0.0.0.0 ip地址，否则本机zk启动会异常：
          # ERROR [zk1/10.0.0.251:3888:QuorumCnxManager$Listener@547] - Exception while listening
          # java.net.BindException: Address not available (Bind failed)错误
          value: server.0=zk-0:2888:3888 server.1=zk-1:2888:3888 server.2=0.0.0.0:2888:3888
        - name: ZOO_DATA_DIR
          value: '/data/zk-data'
        - name: ZOO_DATA_LOG_DIR
          value: '/data/zk-logs'
